### ISSUE TITLE
Unexpected MSRV bump in 0.1.16

### ISSUE THREAD

**Issue by juntyr** [jvo203/zfp-sys#5]
bindgen 0.70 increased the MSRV that is targeted by default by their generated code. Therefore, zfp-sys 0.1.16 increased its MSRV in an update that is automatically picked up by cargo update. In the end, this broke my build without me asking for a breaking change.

I think there are a few options now for addressing the issue. In any case, zfp-sys will need its own MSRV policy. bindgen has the https://docs.rs/bindgen/latest/bindgen/struct.Builder.html#method.rust_target method to select which Rust version to target at build time. It would be ideal for zfp-sys to pick one explicitly instead of always using the largest one.

a) If the MSRV bump was intended, zfp-sys 0.1.16 should be yanked from crates.io and re-released as 0.2.0

b) If the MSRV bump was unintended, you could choose any target version below 1.77, set it in the build script, and release this version on crates.io as 0.1.17

Thank you for your help with this issue, and of course for developing this crate!

**Comment by jvo203** [comment]
Thank you for reporting this problem and sorry for the inconvenience. Indeed it was an unintended consequence of bumping bindgen.

Personally I am somewhat apprehensive about artificially limiting the Rust version so it might be a good time to bump zfp-sys to 0.2.0 and accept the default policy from bindgen.

**Comment by jvo203** [comment]
Done, yanked the offending version and re-released it as 0.2.0. If there any more problems please re-open the issue.

**Comment by juntyr** [comment]
Thank you for the quick action!
